build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: joshdvir/drone-ecs
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: joshdvir/drone-ecs
    tag: latest
    when:
      branch: release/0.4
      event: push

plugin:
  name: ECS
  desc: Deploy or update a project on AWS ECS
  type: deploy
  image: joshdvir/drone-ecs
  labels:
    - aws
    - paas
